In [4]:
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display

# Kết nối tới PostgreSQL
engine = create_engine('postgresql+psycopg2://airflow:airflow@localhost:5434/airflow')

# Đọc bảng raw_customers từ schema raw_retails_data
df = pd.read_sql('SELECT * FROM raw_retails_data.raw_customers', engine)

# Hiển thị 5 dòng đầu
display(df.head())

,customer_id,name,email,phone,loyalty_program_id,gender,age,created_at
0,1,Customer 1,cust1@example.com,1234567891,3,2021-04-28,None,None
1,2,Customer 2,cust2@example.com,1234567892,5,2021-07-01,None,None
2,3,Customer 3,cust3@example.com,1234567893,3,2023-01-23,None,None
3,4,Customer 4,cust4@example.com,1234567894,1,2022-05-28,None,None
4,5,Customer 5,cust5@example.com,1234567895,5,2098-01-21,None,None

In [6]:
# # Kích thước dataframe
# print("Shape:", df.shape)

# # Các cột và kiểu dữ liệu
# print("\nColumn info:")
# print(df.dtypes)

# # Thống kê mô tả
# print("\nDescribe numerical features:")
# print(df.describe())

# # Thống kê cho cột dạng object (chuỗi)
# print("\nDescribe categorical features:")
# print(df.describe(include='object'))

# Tỉ lệ thiếu dữ liệu
print("\nMissing values per column:")
print(df.isnull().sum())

Missing values per column:
customer_id              0
name                     0
email                    0
phone                    0
loyalty_program_id       0
gender                   0
age                   1000
created_at            1000
dtype: int64